language: scala

# only trigger builds on master
branches:
  only:
    - master

before_script:
  - sudo chmod +x /usr/local/bin/sbt

script:
  - sbt clean coverage test coverageReport coverageAggregate

before_install:
    - pip install --user codecov

after_success:
  - codecov

jdk:
  - oraclejdk8
