language: scala

# only trigger builds on master
branches:
  only:
    - master

before_script:
  - sudo chmod +x /usr/local/bin/sbt

script:
  - sbt clean coverage test coverageReport coverageAggregate

scala:
   - 2.10.6
   - 2.11.11
   - 2.12.2

before_install:
    - pip install --user codecov

after_success:
  - codecov

jdk:
  - oraclejdk8
